Fix number compare: remove subtract from substeps
- Simpler implementation for `_$decimalCompare` that doesn't rely on `DigitList.Subtract` and should have less performance overhead.
- "Type instantiation is excessively deep..." error persists for test case `42.04, 42.02`, but no longer occurs for `42.02, 42.04`.

- Anomaly: Replacing `A_DONE, B_DONE` in line 43 with their defaults from lines 39-40 results in the following error. Possible bug in `Boolean._$and` or `Conditional._$equals`?
```
error TS2344: Type '0 | 1 | -1' does not satisfy the constraint '1 & _'.
  Type '0' is not assignable to type '1 & _'.
    Type '0' is not assignable to type '1'.
```